<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Court;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class CourtSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get a court owner user or create one
        $courtOwner = User::where('role', 'court_owner')->first();
        if (!$courtOwner) {
            $courtOwner = User::where('role', 'admin')->first();
        }
        if (!$courtOwner) {
            $courtOwner = User::first();
        }

        $courts = [
            [
                'owner_id' => $courtOwner->id,
                'name' => 'Downtown Pickleball Arena',
                'description' => 'Premier indoor pickleball facility in the heart of Cebu City with 8 professional courts, air-conditioned playing area, and modern amenities.',
                'type' => 'indoor',
                'surface' => 'sport_court',
                'address' => '123 Osmena Boulevard',
                'city' => 'Cebu City',
                'state_province' => 'Cebu',
                'country' => 'Philippines',
                'postal_code' => '6000',
                'latitude' => 10.3157,
                'longitude' => 123.8854,
                'number_of_courts' => 8,
                'amenities' => ['parking', 'restrooms', 'lighting', 'water', 'seating', 'lockers', 'shower', 'pro_shop'],
                'hours_of_operation' => [
                    'monday' => ['open' => '06:00', 'close' => '22:00'],
                    'tuesday' => ['open' => '06:00', 'close' => '22:00'],
                    'wednesday' => ['open' => '06:00', 'close' => '22:00'],
                    'thursday' => ['open' => '06:00', 'close' => '22:00'],
                    'friday' => ['open' => '06:00', 'close' => '23:00'],
                    'saturday' => ['open' => '07:00', 'close' => '23:00'],
                    'sunday' => ['open' => '07:00', 'close' => '22:00'],
                ],
                'is_free' => false,
                'price_per_hour' => 500.00,
                'peak_hour_price' => 700.00,
                'phone_number' => '+63 32 123 4567',
                'email' => 'info@downtownpickleball.com',
                'website' => 'https://downtownpickleball.com',
                'requires_booking' => true,
                'booking_url' => 'https://downtownpickleball.com/book',
                'status' => 'approved',
                'rating' => 4.9,
                'total_reviews' => 124,
                'total_bookings' => 856,
                'view_count' => 2341,
                'is_featured' => true,
                'is_active' => true,
                'approved_at' => now()->subDays(30),
            ],
            [
                'owner_id' => $courtOwner->id,
                'name' => 'Mountain View Courts',
                'description' => 'Beautiful outdoor courts with stunning mountain views. Perfect for morning and afternoon play.',
                'type' => 'outdoor',
                'surface' => 'concrete',
                'address' => '456 Busay Road',
                'city' => 'Cebu City',
                'state_province' => 'Cebu',
                'country' => 'Philippines',
                'postal_code' => '6000',
                'latitude' => 10.3599,
                'longitude' => 123.8667,
                'number_of_courts' => 4,
                'amenities' => ['parking', 'restrooms', 'water', 'seating'],
                'hours_of_operation' => [
                    'monday' => ['open' => '05:00', 'close' => '20:00'],
                    'tuesday' => ['open' => '05:00', 'close' => '20:00'],
                    'wednesday' => ['open' => '05:00', 'close' => '20:00'],
                    'thursday' => ['open' => '05:00', 'close' => '20:00'],
                    'friday' => ['open' => '05:00', 'close' => '20:00'],
                    'saturday' => ['open' => '06:00', 'close' => '20:00'],
                    'sunday' => ['open' => '06:00', 'close' => '20:00'],
                ],
                'is_free' => false,
                'price_per_hour' => 300.00,
                'phone_number' => '+63 32 234 5678',
                'email' => 'mountainview@courts.ph',
                'requires_booking' => true,
                'status' => 'pending',
                'rating' => 0.00,
                'total_reviews' => 0,
                'total_bookings' => 0,
                'view_count' => 45,
                'is_active' => true,
            ],
            [
                'owner_id' => $courtOwner->id,
                'name' => 'The Smash Club',
                'description' => 'Exclusive members club with professional coaching available. Indoor facility with premium amenities.',
                'type' => 'indoor',
                'surface' => 'wood',
                'address' => '789 A.S. Fortuna St',
                'city' => 'Mandaue City',
                'state_province' => 'Cebu',
                'country' => 'Philippines',
                'postal_code' => '6014',
                'latitude' => 10.3240,
                'longitude' => 123.9422,
                'number_of_courts' => 6,
                'amenities' => ['parking', 'restrooms', 'lighting', 'water', 'seating', 'lockers', 'shower', 'cafe', 'pro_shop'],
                'hours_of_operation' => [
                    'monday' => ['open' => '06:00', 'close' => '22:00'],
                    'tuesday' => ['open' => '06:00', 'close' => '22:00'],
                    'wednesday' => ['open' => '06:00', 'close' => '22:00'],
                    'thursday' => ['open' => '06:00', 'close' => '22:00'],
                    'friday' => ['open' => '06:00', 'close' => '23:00'],
                    'saturday' => ['open' => '07:00', 'close' => '23:00'],
                    'sunday' => ['open' => '07:00', 'close' => '22:00'],
                ],
                'is_free' => false,
                'price_per_hour' => 600.00,
                'peak_hour_price' => 800.00,
                'phone_number' => '+63 32 345 6789',
                'email' => 'info@smashclub.ph',
                'website' => 'https://smashclub.ph',
                'requires_booking' => true,
                'booking_url' => 'https://smashclub.ph/reserve',
                'status' => 'approved',
                'rating' => 4.7,
                'total_reviews' => 89,
                'total_bookings' => 543,
                'view_count' => 1567,
                'is_featured' => true,
                'is_active' => true,
                'approved_at' => now()->subDays(45),
            ],
            [
                'owner_id' => $courtOwner->id,
                'name' => 'Seaside Pickleball Park',
                'description' => 'Public outdoor courts by the sea. Free to play with beautiful sunset views.',
                'type' => 'outdoor',
                'surface' => 'asphalt',
                'address' => 'South Road Properties',
                'city' => 'Cebu City',
                'state_province' => 'Cebu',
                'country' => 'Philippines',
                'postal_code' => '6000',
                'latitude' => 10.2777,
                'longitude' => 123.8769,
                'number_of_courts' => 3,
                'amenities' => ['parking', 'restrooms', 'water', 'seating', 'lighting'],
                'hours_of_operation' => [
                    'monday' => ['open' => '05:00', 'close' => '21:00'],
                    'tuesday' => ['open' => '05:00', 'close' => '21:00'],
                    'wednesday' => ['open' => '05:00', 'close' => '21:00'],
                    'thursday' => ['open' => '05:00', 'close' => '21:00'],
                    'friday' => ['open' => '05:00', 'close' => '21:00'],
                    'saturday' => ['open' => '05:00', 'close' => '21:00'],
                    'sunday' => ['open' => '05:00', 'close' => '21:00'],
                ],
                'is_free' => true,
                'price_per_hour' => null,
                'phone_number' => '+63 32 456 7890',
                'requires_booking' => false,
                'status' => 'approved',
                'rating' => 4.5,
                'total_reviews' => 67,
                'total_bookings' => 234,
                'view_count' => 987,
                'is_active' => true,
                'approved_at' => now()->subDays(60),
            ],
            [
                'owner_id' => $courtOwner->id,
                'name' => 'Elite Sports Complex',
                'description' => 'Multi-sport facility with dedicated pickleball courts. Both indoor and outdoor options available.',
                'type' => 'both',
                'surface' => 'sport_court',
                'address' => '321 Banilad Road',
                'city' => 'Cebu City',
                'state_province' => 'Cebu',
                'country' => 'Philippines',
                'postal_code' => '6000',
                'latitude' => 10.3455,
                'longitude' => 123.9125,
                'number_of_courts' => 10,
                'amenities' => ['parking', 'restrooms', 'lighting', 'water', 'seating', 'lockers', 'shower', 'cafe', 'gym'],
                'hours_of_operation' => [
                    'monday' => ['open' => '06:00', 'close' => '23:00'],
                    'tuesday' => ['open' => '06:00', 'close' => '23:00'],
                    'wednesday' => ['open' => '06:00', 'close' => '23:00'],
                    'thursday' => ['open' => '06:00', 'close' => '23:00'],
                    'friday' => ['open' => '06:00', 'close' => '24:00'],
                    'saturday' => ['open' => '06:00', 'close' => '24:00'],
                    'sunday' => ['open' => '06:00', 'close' => '23:00'],
                ],
                'is_free' => false,
                'price_per_hour' => 450.00,
                'peak_hour_price' => 650.00,
                'phone_number' => '+63 32 567 8901',
                'email' => 'contact@elitesportscomplex.ph',
                'website' => 'https://elitesportscomplex.ph',
                'requires_booking' => true,
                'booking_url' => 'https://elitesportscomplex.ph/booking',
                'status' => 'approved',
                'rating' => 4.8,
                'total_reviews' => 156,
                'total_bookings' => 1234,
                'view_count' => 3456,
                'is_featured' => true,
                'is_active' => true,
                'approved_at' => now()->subDays(90),
            ],
        ];

        foreach ($courts as $court) {
            Court::create($court);
        }
    }
}
